### ISSUE TITLE
Issue running the script with -a

### ISSUE THREAD

**Issue by Remourz** [iustin24/chameleon#19]
When trying the script and using the -a parameter it crashes and gives this

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Permission denied (os error 13)', /cargo/git/checkouts/wappalyzer-e32a3fb79f4ccad3/fb82bb4/src/lib.rs:98:10
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by BugAnnihilator** [comment]
same issue here!
but mine message is : 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by WULINPIN** [comment]
hread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: response doesn't include the content length', /cargo/git/checkouts/wappalyzer-e32a3fb79f4ccad3/fb82bb4/src/lib.rs:98:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
