### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /cargo/git/checkouts/wappalyzer-e32a3fb79f4ccad3/fb82bb4/src/lib.rs:117:39 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [iustin24/chameleon#23]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /cargo/git/checkouts/wappalyzer-e32a3fb79f4ccad3/fb82bb4/src/lib.rs:117:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jacob2020baklas** [comment]
i have the same error , im not any good with rust , if someone can tell me why this is happening i may fix it .
